export default [
  {
    cnName: "CANADA/United States/TURKS AND CAICOS",
    enName: "CANADA/United States/TURKS AND CAICOS",
    dialingCode: "+1",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "British Virgin Islands",
    enName: "British Virgin Islands",
    dialingCode: "+1-284",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BAHAMAS",
    enName: "BAHAMAS",
    dialingCode: "+1242",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BARBADOS",
    enName: "BARBADOS",
    dialingCode: "+1246",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ANGUILLA",
    enName: "ANGUILLA",
    dialingCode: "+1264",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ANTIGUA AND BARBUDA",
    enName: "ANTIGUA AND BARBUDA",
    dialingCode: "+1268",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "U.S. VIRGIN ISLANDS",
    enName: "U.S. VIRGIN ISLANDS",
    dialingCode: "+1340",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CAYMAN ISLANDS",
    enName: "CAYMAN ISLANDS",
    dialingCode: "+1345",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BERMUDA",
    enName: "BERMUDA",
    dialingCode: "+1441",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MONTSERRAT",
    enName: "MONTSERRAT",
    dialingCode: "+1664",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GUAM",
    enName: "GUAM",
    dialingCode: "+1671",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SAINT LUCIA",
    enName: "SAINT LUCIA",
    dialingCode: "+1758",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SAINT VINCENT AND THE GRENADINES",
    enName: "SAINT VINCENT AND THE GRENADINES",
    dialingCode: "+1784",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "PUERTO RICO",
    enName: "PUERTO RICO",
    dialingCode: "+1787",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GRENADA",
    enName: "GRENADA",
    dialingCode: "+1809",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TRINIDAD AND TOBAGO",
    enName: "TRINIDAD AND TOBAGO",
    dialingCode: "+1868",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "JAMAICA",
    enName: "JAMAICA",
    dialingCode: "+1876",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "DOMINICAN REPUBLIC",
    enName: "DOMINICAN REPUBLIC",
    dialingCode: "+1890",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "EGYPT",
    enName: "EGYPT",
    dialingCode: "+20",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SOUTH SUDAN",
    enName: "SOUTH SUDAN",
    dialingCode: "+211",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MOROCCO",
    enName: "MOROCCO",
    dialingCode: "+212",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ALGERIA",
    enName: "ALGERIA",
    dialingCode: "+213",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TUNISIA",
    enName: "TUNISIA",
    dialingCode: "+216",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "LIBYAN ARAB JAMAHIRIYA",
    enName: "LIBYAN ARAB JAMAHIRIYA",
    dialingCode: "+218",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GAMBIA",
    enName: "GAMBIA",
    dialingCode: "+220",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SENEGAL",
    enName: "SENEGAL",
    dialingCode: "+221",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MALI",
    enName: "MALI",
    dialingCode: "+223",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GUINEA",
    enName: "GUINEA",
    dialingCode: "+224",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CÔTE D'IVOIRE",
    enName: "CÔTE D'IVOIRE",
    dialingCode: "+225",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BURKINA FASO",
    enName: "BURKINA FASO",
    dialingCode: "+226",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "NIGER",
    enName: "NIGER",
    dialingCode: "+227",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TOGO",
    enName: "TOGO",
    dialingCode: "+228",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BENIN",
    enName: "BENIN",
    dialingCode: "+229",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MAURITIUS",
    enName: "MAURITIUS",
    dialingCode: "+230",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "LIBERIA",
    enName: "LIBERIA",
    dialingCode: "+231",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SIERRA LEONE",
    enName: "SIERRA LEONE",
    dialingCode: "+232",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GHANA",
    enName: "GHANA",
    dialingCode: "+233",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "NIGERIA",
    enName: "NIGERIA",
    dialingCode: "+234",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CHAD",
    enName: "CHAD",
    dialingCode: "+235",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CENTRAL AFRICAN REPUBLIC",
    enName: "CENTRAL AFRICAN REPUBLIC",
    dialingCode: "+236",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CAMEROON",
    enName: "CAMEROON",
    dialingCode: "+237",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SAO TOME AND PRINCIPE",
    enName: "SAO TOME AND PRINCIPE",
    dialingCode: "+239",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GABON",
    enName: "GABON",
    dialingCode: "+241",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CONGO",
    enName: "CONGO",
    dialingCode: "+242",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ANGOLA",
    enName: "ANGOLA",
    dialingCode: "+244",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SEYCHELLES",
    enName: "SEYCHELLES",
    dialingCode: "+248",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SUDAN",
    enName: "SUDAN",
    dialingCode: "+249",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "Rwanda",
    enName: "Rwanda",
    dialingCode: "+250",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ETHIOPIA",
    enName: "ETHIOPIA",
    dialingCode: "+251",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SOMALIA",
    enName: "SOMALIA",
    dialingCode: "+252",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "DJIBOUTI",
    enName: "DJIBOUTI",
    dialingCode: "+253",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "KENYA",
    enName: "KENYA",
    dialingCode: "+254",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TANZANIA, UNITED REPUBLIC OF",
    enName: "TANZANIA, UNITED REPUBLIC OF",
    dialingCode: "+255",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "UGANDA",
    enName: "UGANDA",
    dialingCode: "+256",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BURUNDI",
    enName: "BURUNDI",
    dialingCode: "+257",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MOZAMBIQUE",
    enName: "MOZAMBIQUE",
    dialingCode: "+258",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ZAMBIA",
    enName: "ZAMBIA",
    dialingCode: "+260",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MADAGASCAR",
    enName: "MADAGASCAR",
    dialingCode: "+261",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "REUNION",
    enName: "REUNION",
    dialingCode: "+262",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ZIMBABWE",
    enName: "ZIMBABWE",
    dialingCode: "+263",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "NAMIBIA",
    enName: "NAMIBIA",
    dialingCode: "+264",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MALAWI",
    enName: "MALAWI",
    dialingCode: "+265",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "LESOTHO",
    enName: "LESOTHO",
    dialingCode: "+266",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BOTSWANA",
    enName: "BOTSWANA",
    dialingCode: "+267",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SWAZILAND",
    enName: "SWAZILAND",
    dialingCode: "+268",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SOUTH AFRICA",
    enName: "SOUTH AFRICA",
    dialingCode: "+27",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GREECE",
    enName: "GREECE",
    dialingCode: "+30",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "NETHERLANDS",
    enName: "NETHERLANDS",
    dialingCode: "+31",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BELGIUM",
    enName: "BELGIUM",
    dialingCode: "+32",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "FRANCE",
    enName: "FRANCE",
    dialingCode: "+33",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "KYRGYZSTAN",
    enName: "KYRGYZSTAN",
    dialingCode: "+331",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SPAIN",
    enName: "SPAIN",
    dialingCode: "+34",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ÅLAND ISLANDS",
    enName: "ÅLAND ISLANDS",
    dialingCode: "+340",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GIBRALTAR",
    enName: "GIBRALTAR",
    dialingCode: "+350",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "PORTUGAL",
    enName: "PORTUGAL",
    dialingCode: "+351",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "LUXEMBOURG",
    enName: "LUXEMBOURG",
    dialingCode: "+352",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "IRELAND",
    enName: "IRELAND",
    dialingCode: "+353",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ICELAND",
    enName: "ICELAND",
    dialingCode: "+354",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ALBANIA",
    enName: "ALBANIA",
    dialingCode: "+355",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MALTA",
    enName: "MALTA",
    dialingCode: "+356",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CYPRUS",
    enName: "CYPRUS",
    dialingCode: "+357",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "FINLAND",
    enName: "FINLAND",
    dialingCode: "+358",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BULGARIA",
    enName: "BULGARIA",
    dialingCode: "+359",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "HUNGARY",
    enName: "HUNGARY",
    dialingCode: "+36",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "LITHUANIA",
    enName: "LITHUANIA",
    dialingCode: "+370",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "LATVIA",
    enName: "LATVIA",
    dialingCode: "+371",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ESTONIA",
    enName: "ESTONIA",
    dialingCode: "+372",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MOLDOVA, REPUBLIC OF",
    enName: "MOLDOVA, REPUBLIC OF",
    dialingCode: "+373",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ARMENIA",
    enName: "ARMENIA",
    dialingCode: "+374",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BELARUS",
    enName: "BELARUS",
    dialingCode: "+375",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ANDORRA",
    enName: "ANDORRA",
    dialingCode: "+376",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MONACO",
    enName: "MONACO",
    dialingCode: "+377",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SAN MARINO",
    enName: "SAN MARINO",
    dialingCode: "+378",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "VATICAN CITY",
    enName: "VATICAN CITY",
    dialingCode: "+379",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "UKRAINE",
    enName: "UKRAINE",
    dialingCode: "+380",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SERBIA",
    enName: "SERBIA",
    dialingCode: "+381",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CROATIA",
    enName: "CROATIA",
    dialingCode: "+385",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SLOVENIA",
    enName: "SLOVENIA",
    dialingCode: "+386",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ITALY",
    enName: "ITALY",
    dialingCode: "+39",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ROMANIA",
    enName: "ROMANIA",
    dialingCode: "+40",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SWITZERLAND",
    enName: "SWITZERLAND",
    dialingCode: "+41",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CZECH REPUBLIC",
    enName: "CZECH REPUBLIC",
    dialingCode: "+420",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SLOVAKIA",
    enName: "SLOVAKIA",
    dialingCode: "+421",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "LIECHTENSTEIN",
    enName: "LIECHTENSTEIN",
    dialingCode: "+423",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "AUSTRIA",
    enName: "AUSTRIA",
    dialingCode: "+43",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "UNITED KINGDOM",
    enName: "UNITED KINGDOM",
    dialingCode: "+44",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "DENMARK",
    enName: "DENMARK",
    dialingCode: "+45",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SWEDEN",
    enName: "SWEDEN",
    dialingCode: "+46",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "NORWAY",
    enName: "NORWAY",
    dialingCode: "+47",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "POLAND",
    enName: "POLAND",
    dialingCode: "+48",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GERMANY",
    enName: "GERMANY",
    dialingCode: "+49",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BELIZE",
    enName: "BELIZE",
    dialingCode: "+501",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GUATEMALA",
    enName: "GUATEMALA",
    dialingCode: "+502",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "EL SALVADOR",
    enName: "EL SALVADOR",
    dialingCode: "+503",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "HONDURAS",
    enName: "HONDURAS",
    dialingCode: "+504",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "NICARAGUA",
    enName: "NICARAGUA",
    dialingCode: "+505",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "COSTA RICA",
    enName: "COSTA RICA",
    dialingCode: "+506",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "PANAMA",
    enName: "PANAMA",
    dialingCode: "+507",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "HAITI",
    enName: "HAITI",
    dialingCode: "+509",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "PERU",
    enName: "PERU",
    dialingCode: "+51",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MEXICO",
    enName: "MEXICO",
    dialingCode: "+52",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CUBA",
    enName: "CUBA",
    dialingCode: "+53",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ARGENTINA",
    enName: "ARGENTINA",
    dialingCode: "+54",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BRAZIL",
    enName: "BRAZIL",
    dialingCode: "+55",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CHILE",
    enName: "CHILE",
    dialingCode: "+56",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "COLOMBIA",
    enName: "COLOMBIA",
    dialingCode: "+57",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "VENEZUELA, BOLIVARIAN REPUBLIC OF",
    enName: "VENEZUELA, BOLIVARIAN REPUBLIC OF",
    dialingCode: "+58",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BOLIVIA, PLURINATIONAL STATE OF",
    enName: "BOLIVIA, PLURINATIONAL STATE OF",
    dialingCode: "+591",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GUYANA",
    enName: "GUYANA",
    dialingCode: "+592",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ECUADOR",
    enName: "ECUADOR",
    dialingCode: "+593",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "FRENCH GUIANA",
    enName: "FRENCH GUIANA",
    dialingCode: "+594",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "PARAGUAY",
    enName: "PARAGUAY",
    dialingCode: "+595",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MARTINIQUE",
    enName: "MARTINIQUE",
    dialingCode: "+596",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SURINAME",
    enName: "SURINAME",
    dialingCode: "+597",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "URUGUAY",
    enName: "URUGUAY",
    dialingCode: "+598",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "NETHERLANDS ANTILLES",
    enName: "NETHERLANDS ANTILLES",
    dialingCode: "+599",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MALAYSIA",
    enName: "MALAYSIA",
    dialingCode: "+60",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "AUSTRALIA",
    enName: "AUSTRALIA",
    dialingCode: "+61",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "INDONESIA",
    enName: "INDONESIA",
    dialingCode: "+62",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "PHILIPPINES",
    enName: "PHILIPPINES",
    dialingCode: "+63",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "NEW ZEALAND",
    enName: "NEW ZEALAND",
    dialingCode: "+64",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SINGAPORE",
    enName: "SINGAPORE",
    dialingCode: "+65",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "THAILAND",
    enName: "THAILAND",
    dialingCode: "+66",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TIMOR-LESTE (EAST TIMOR)",
    enName: "TIMOR-LESTE (EAST TIMOR)",
    dialingCode: "+670",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BRUNEI DARUSSALAM",
    enName: "BRUNEI DARUSSALAM",
    dialingCode: "+673",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "NAURU",
    enName: "NAURU",
    dialingCode: "+674",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "PAPUA NEW GUINEA",
    enName: "PAPUA NEW GUINEA",
    dialingCode: "+675",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TONGA",
    enName: "TONGA",
    dialingCode: "+676",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SOLOMON ISLANDS",
    enName: "SOLOMON ISLANDS",
    dialingCode: "+677",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "VANUATU",
    enName: "VANUATU",
    dialingCode: "+678",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "FIJI",
    enName: "FIJI",
    dialingCode: "+679",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "WALLIS AND FUTUNA",
    enName: "WALLIS AND FUTUNA",
    dialingCode: "+681",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "COOK ISLANDS",
    enName: "COOK ISLANDS",
    dialingCode: "+682",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "AMERICAN SAMOA",
    enName: "AMERICAN SAMOA",
    dialingCode: "+684",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SAMOA",
    enName: "SAMOA",
    dialingCode: "+685",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TUVALU",
    enName: "TUVALU",
    dialingCode: "+688",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "FRENCH POLYNESIA",
    enName: "FRENCH POLYNESIA",
    dialingCode: "+689",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TOKELAU",
    enName: "TOKELAU",
    dialingCode: "+690",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "RUSSIAN FEDERATION/KAZAKHSTAN",
    enName: "RUSSIAN FEDERATION/KAZAKHSTAN",
    dialingCode: "+7",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SINT MAARTEN",
    enName: "SINT MAARTEN",
    dialingCode: "+721",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "JAPAN",
    enName: "JAPAN",
    dialingCode: "+81",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "KOREA, REPUBLIC OF",
    enName: "KOREA, REPUBLIC OF",
    dialingCode: "+82",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "VIET NAM",
    enName: "VIET NAM",
    dialingCode: "+84",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
    enName: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
    dialingCode: "+850",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "HONG KONG",
    enName: "HONG KONG",
    dialingCode: "+852",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MACAO",
    enName: "MACAO",
    dialingCode: "+853",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CAMBODIA",
    enName: "CAMBODIA",
    dialingCode: "+855",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    enName: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    dialingCode: "+856",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "CHINA",
    enName: "CHINA",
    dialingCode: "+86",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BANGLADESH",
    enName: "BANGLADESH",
    dialingCode: "+880",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TAIWAN",
    enName: "TAIWAN",
    dialingCode: "+886",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TURKEY",
    enName: "TURKEY",
    dialingCode: "+90",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "INDIA",
    enName: "INDIA",
    dialingCode: "+91",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "PAKISTAN",
    enName: "PAKISTAN",
    dialingCode: "+92",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "AFGHANISTAN",
    enName: "AFGHANISTAN",
    dialingCode: "+93",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SRI LANKA",
    enName: "SRI LANKA",
    dialingCode: "+94",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MYANMAR",
    enName: "MYANMAR",
    dialingCode: "+95",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MALDIVES",
    enName: "MALDIVES",
    dialingCode: "+960",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "LEBANON",
    enName: "LEBANON",
    dialingCode: "+961",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "JORDAN",
    enName: "JORDAN",
    dialingCode: "+962",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SYRIAN ARAB REPUBLIC",
    enName: "SYRIAN ARAB REPUBLIC",
    dialingCode: "+963",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "IRAQ",
    enName: "IRAQ",
    dialingCode: "+964",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "KUWAIT",
    enName: "KUWAIT",
    dialingCode: "+965",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "SAUDI ARABIA",
    enName: "SAUDI ARABIA",
    dialingCode: "+966",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "YEMEN",
    enName: "YEMEN",
    dialingCode: "+967",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "OMAN",
    enName: "OMAN",
    dialingCode: "+968",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "UNITED ARAB EMIRATES",
    enName: "UNITED ARAB EMIRATES",
    dialingCode: "+971",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "ISRAEL",
    enName: "ISRAEL",
    dialingCode: "+972",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "BAHRAIN",
    enName: "BAHRAIN",
    dialingCode: "+973",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "QATAR",
    enName: "QATAR",
    dialingCode: "+974",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "MONGOLIA",
    enName: "MONGOLIA",
    dialingCode: "+976",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "NEPAL",
    enName: "NEPAL",
    dialingCode: "+977",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "IRAN, ISLAMIC REPUBLIC OF",
    enName: "IRAN, ISLAMIC REPUBLIC OF",
    dialingCode: "+98",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TAJIKISTAN",
    enName: "TAJIKISTAN",
    dialingCode: "+992",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "TURKMENISTAN",
    enName: "TURKMENISTAN",
    dialingCode: "+993",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "AZERBAIJAN",
    enName: "AZERBAIJAN",
    dialingCode: "+994",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "GEORGIA",
    enName: "GEORGIA",
    dialingCode: "+995",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
  {
    cnName: "UZBEKISTAN",
    enName: "UZBEKISTAN",
    dialingCode: "+998",
    flag: "https://raw.githubusercontent.com/lipis/flag-icons/refs/heads/main/flags/1x1/bi.svg",
  },
];
